# Generated by Django 2.2.4 on 2019-08-17 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=1000, verbose_name='アクセストークン')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='レコード生成日時')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='レコード更新日時')),
            ],
        ),
    ]
